// rhythms.js - ECG rhythm parameter definitions
// VERSION: Updated paced_vvi for new pacedGenerator. Added atrial_paced example.
//          Clarified t_mean_offset meaning for new pacedGenerator.
//          MODIFIED: paced_vvi to show native P -> spike -> negative QRS -> positive T.
//          ADJUSTED: paced_vvi: Increased distance between native P and spike, increased spike amplitude.
//          ADDED: vf_hold_duration parameter to vf and fine_vf rhythms.
//          MODIFIED: cpr_artifact respiratoryRate to 10, as per user request.
//          MODIFIED: PEA rhythm parameters to be more agonal-like.

export const RHYTHM_PARAMS = {
  // --- Sinus Rhythms & Variations ---
  normal: {
    generatorType: "pqrst",
    baseHR: 75,
    isFlat: false,
    isChaotic: false,
    hasP: true,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.02,
    p_amp: 0.15,
    qrs_amp: 1.3,
    qrs_width: 0.08,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: 0.28,
    t_width: 0.07,
    pr_interval: 0.16,
    t_mean_offset: 0.25, // For pqrstGenerator: offset from t_relative=0 to T-center (via pr_interval)
    noise_amp: 0.015,
  },
  brady: {
    generatorType: "pqrst",
    baseHR: 45,
    isFlat: false,
    isChaotic: false,
    hasP: true,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.03,
    p_amp: 0.15,
    qrs_amp: 1.3,
    qrs_width: 0.08,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: 0.28,
    t_width: 0.07,
    pr_interval: 0.17,
    t_mean_offset: 0.26,
    noise_amp: 0.015,
  },
  tachy: {
    generatorType: "pqrst",
    baseHR: 120,
    isFlat: false,
    isChaotic: false,
    hasP: true,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.05,
    p_amp: 0.12,
    qrs_amp: 1.2,
    qrs_width: 0.07,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: 0.25,
    t_width: 0.06,
    pr_interval: 0.14,
    t_mean_offset: 0.22,
    noise_amp: 0.02,
  },
  sinus_arrhythmia: {
    generatorType: "pqrst",
    baseHR: 70,
    isFlat: false,
    isChaotic: false,
    hasP: true,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.2,
    p_amp: 0.15,
    qrs_amp: 1.3,
    qrs_width: 0.08,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: 0.28,
    t_width: 0.07,
    pr_interval: 0.16,
    t_mean_offset: 0.25,
    noise_amp: 0.015,
  },
  sinus_t_inversion: {
    generatorType: "pqrst",
    baseHR: 70,
    isFlat: false,
    isChaotic: false,
    hasP: true,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.02,
    p_amp: 0.15,
    qrs_amp: 1.3,
    qrs_width: 0.08,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: -0.2,
    t_width: 0.08,
    pr_interval: 0.16,
    t_mean_offset: 0.25,
    noise_amp: 0.015,
  },
  sinus_st_depression: {
    generatorType: "pqrst",
    baseHR: 80,
    isFlat: false,
    isChaotic: false,
    hasP: true,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.02,
    p_amp: 0.15,
    qrs_amp: 1.3,
    qrs_width: 0.08,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: 0.25,
    t_width: 0.07,
    pr_interval: 0.16,
    t_mean_offset: 0.25,
    st_elevation_amp: -0.2,
    noise_amp: 0.015,
  },
  hyperkalemia_peaked_t: {
    generatorType: "pqrst",
    baseHR: 40,
    isFlat: false,
    isChaotic: false,
    hasP: true,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.03,
    p_amp: 0.12,
    qrs_amp: 1.2,
    qrs_width: 0.09,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: 1.9,
    t_width: 0.035,
    pr_interval: 0.2,
    t_mean_offset: 0.25,
    noise_amp: 0.02,
  },

  // --- Atrial / Supraventricular Rhythms ---
  afib: {
    generatorType: "pqrst",
    baseHR: 110,
    isFlat: false,
    isChaotic: false,
    hasP: false,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.4,
    p_amp: 0,
    qrs_amp: 1.2,
    qrs_width: 0.08,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: 0.25,
    t_width: 0.07,
    pr_interval: 0,
    t_mean_offset: 0.22,
    noise_amp: 0.03,
  },
  svt: {
    generatorType: "pqrst",
    baseHR: 180,
    isFlat: false,
    isChaotic: false,
    hasP: false,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.01,
    p_amp: 0,
    qrs_amp: 1.1,
    qrs_width: 0.07,
    q_amp_factor: 0.05,
    s_amp_factor: 0.1,
    t_amp: 0.2,
    t_width: 0.06,
    pr_interval: 0,
    t_mean_offset: 0.15,
    noise_amp: 0.015,
  },

  // --- Junctional Rhythms ---
  junctional: {
    generatorType: "pqrst",
    baseHR: 50,
    isFlat: false,
    isChaotic: false,
    hasP: false,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.02,
    p_amp: 0,
    qrs_amp: 1.2,
    qrs_width: 0.08,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: 0.28,
    t_width: 0.07,
    pr_interval: 0,
    t_mean_offset: 0.25,
    noise_amp: 0.015,
  },
  junctional_tachy: {
    generatorType: "pqrst",
    baseHR: 110,
    isFlat: false,
    isChaotic: false,
    hasP: false,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.01,
    p_amp: 0,
    qrs_amp: 1.2,
    qrs_width: 0.08,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: 0.28,
    t_width: 0.07,
    pr_interval: 0,
    t_mean_offset: 0.2,
    noise_amp: 0.015,
  },

  // --- Ventricular Rhythms (Perfusing) ---
  vt: {
    generatorType: "pqrst",
    baseHR: 180,
    isFlat: false,
    isChaotic: false,
    hasP: false,
    hasT: false,
    isPEA: false,
    isArtifact: false,
    irregular: 0.01,
    p_amp: 0,
    qrs_amp: 1.5,
    qrs_width: 0.16,
    q_amp_factor: 0.05,
    s_amp_factor: 0.1,
    t_amp: -0.2,
    t_width: 0.1,
    pr_interval: 0,
    t_mean_offset: 0.2,
    noise_amp: 0.02,
    spo2Value: 88,
    spo2Shape: "low_perfusion",
    abpSys: 75,
    abpDia: 50,
    abpShape: "normal",
    etco2ValueKpa: 2.7,
    respiratoryRate: 22,
  },
  idio: {
    generatorType: "pqrst",
    baseHR: 30,
    isFlat: false,
    isChaotic: false,
    hasP: false,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.02,
    p_amp: 0,
    qrs_amp: 1.4,
    qrs_width: 0.16,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: -0.3,
    t_width: 0.12,
    pr_interval: 0,
    t_mean_offset: 0.28,
    noise_amp: 0.02,
  },
  aivr: {
    generatorType: "pqrst",
    baseHR: 70,
    isFlat: false,
    isChaotic: false,
    hasP: false,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.02,
    p_amp: 0,
    qrs_amp: 1.4,
    qrs_width: 0.16,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: -0.3,
    t_width: 0.12,
    pr_interval: 0,
    t_mean_offset: 0.28,
    noise_amp: 0.02,
  },
  agonal: {
    generatorType: "pqrst",
    baseHR: 15,
    isFlat: false,
    isChaotic: false,
    hasP: false,
    hasT: true,
    isPEA: false,
    irregular: 0.05,
    p_amp: 0,
    qrs_amp: 1.2,
    qrs_width: 0.18,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: -0.2,
    t_width: 0.15,
    pr_interval: 0,
    t_mean_offset: 0.3,
    noise_amp: 0.03,
    isArtifact: false,
  },

  // --- Conduction Blocks ---
  avb1: {
    generatorType: "pqrst",
    baseHR: 70,
    isFlat: false,
    isChaotic: false,
    hasP: true,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.02,
    p_amp: 0.15,
    qrs_amp: 1.3,
    qrs_width: 0.08,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: 0.28,
    t_width: 0.07,
    pr_interval: 0.24,
    t_mean_offset: 0.25 + (0.24 - 0.16),
    noise_amp: 0.015,
  },
  avb2m1: {
    generatorType: "avBlock",
    blockType: "mobitz1",
    baseHR: 60,
    atrialRate: 80,
    isFlat: false,
    isChaotic: false,
    hasP: true,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.05,
    p_amp: 0.15,
    qrs_amp: 1.2,
    qrs_width: 0.08,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: 0.25,
    t_width: 0.07,
    prIntervalStart: 0.16,
    prIncrement: 0.06,
    wenckebachRatioBeats: 4,
    noise_amp: 0.02,
  },
  avb2m2: {
    generatorType: "avBlock",
    blockType: "mobitz2",
    baseHR: 40,
    atrialRate: 80,
    isFlat: false,
    isChaotic: false,
    hasP: true,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.03,
    p_amp: 0.15,
    qrs_amp: 1.2,
    qrs_width: 0.14,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: 0.2,
    t_width: 0.08,
    prIntervalFixed: 0.18,
    conductionProbability: 0.5,
    escapeEnabled: true,
    escapeRate: 40,
    noise_amp: 0.02,
  },
  avb3: {
    generatorType: "avBlock",
    blockType: "avb3",
    baseHR: 35,
    atrialRate: 75,
    isFlat: false,
    isChaotic: false,
    hasP: true,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.02,
    p_amp: 0.16,
    qrs_amp: 1.3,
    qrs_width: 0.16,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: -0.25,
    t_width: 0.1,
    prIntervalFixed: 0,
    noise_amp: 0.025,
  },

  // --- Injury / Ischemia Patterns ---
  stemi: {
    generatorType: "pqrst",
    baseHR: 85,
    isFlat: false,
    isChaotic: false,
    hasP: true,
    hasT: true,
    isPEA: false,
    isArtifact: false,
    irregular: 0.03,
    p_amp: 0.15,
    qrs_amp: 1.2,
    qrs_width: 0.09,
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,
    t_amp: 0.35,
    t_width: 0.08,
    pr_interval: 0.16,
    t_mean_offset: 0.25,
    noise_amp: 0.015,
    st_elevation_amp: 0.4,
  },

  // --- Paced Rhythms (using NEW pacedGenerator) ---
  paced_vvi: {
    generatorType: "paced",
    baseHR: 70,
    isFlat: false,
    isChaotic: false,
    isPEA: false,
    isArtifact: false,
    irregular: 0.01,
    noise_amp: 0.02,

    hasP: true, // Native P-wave
    p_amp: 0.1, // Amplitude of native P-wave
    pr_interval: 0.16, // PR interval for native P-wave (QRS start if native P conducts)

    hasPacingSpike: true, // Whether to show a pacing spike
    pacing_spike_amp: 1.5, // Amplitude of the pacing spike
    pacing_spike_duration: 0.02, // Duration of the pacing spike
    pacing_spike_pr_offset: 0.15, // Time from t_relative=0 to the start of pacing spike
    // (allows native P before spike)
    qrs_start_after_spike_delay: 0.04, // Time from pacing spike start to QRS start
    qrs_amp: -1.2, // QRS amplitude (can be negative for paced beats)
    pacedQrsWidth: 0.14, // Specific QRS width for paced beats
    q_amp_factor: 0.05, // Q wave amplitude factor relative to qrs_amp
    s_amp_factor: 0.25, // S wave amplitude factor relative to qrs_amp

    hasT: true, // T-wave presence
    t_amp: 0.3, // T-wave amplitude
    pacedTWaveWidth: 0.12, // Specific T-wave width for paced beats
    // For pacedGenerator: t_mean_offset is from QRS START to T-wave center
    t_mean_offset: 0.4,

    st_elevation_amp: 0, // ST segment elevation/depression
  },

  atrial_paced: {
    generatorType: "paced",
    baseHR: 75, // This will be the pacing rate if no other HR source dictates
    isFlat: false,
    isChaotic: false,
    isPEA: false,
    isArtifact: false,
    irregular: 0.02,
    noise_amp: 0.015,

    hasPacingSpike: true, // Show the atrial pacing spike
    pacing_spike_amp: 0.3, // Amplitude of the atrial pacing spike
    pacing_spike_duration: 0.02, // Duration of the atrial pacing spike
    pacing_spike_pr_offset: 0.0, // Atrial spike occurs at the beginning of the cycle (t_relative=0)

    hasP: false, // No native P-wave in this example (atrial pacing overrides)
    p_amp: 0,
    pr_interval: 0.16, // This would be the PR if a native P conducted, but not used here

    // QRS starts after the atrial spike + a PR-like interval
    qrs_start_after_spike_delay: 0.16,
    qrs_amp: 1.3, // Normal QRS amplitude
    qrs_width: 0.08, // Normal QRS width
    q_amp_factor: 0.1,
    s_amp_factor: 0.15,

    hasT: true,
    t_amp: 0.28,
    t_width: 0.07,
    // For pacedGenerator: t_mean_offset is from QRS START to T-wave center
    t_mean_offset: 0.25, // Standard T-wave offset from QRS start

    st_elevation_amp: 0,
  },

  // --- Pulseless Rhythms / Artifacts ---
  vf: {
    generatorType: "chaotic",
    baseHR: 0,
    isFlat: false,
    isChaotic: true,
    hasP: false,
    hasT: false,
    isPEA: false,
    isArtifact: false,
    irregular: 1.0,
    p_amp: 0,
    qrs_amp: 0,
    t_amp: 0,
    vf_amp: 1.5,
    noise_amp: 0.03,
    vf_hold_duration: 4, // Pidetään arvoa 4 näytteen ajan
  },
  fine_vf: {
    generatorType: "chaotic",
    baseHR: 0,
    isFlat: false,
    isChaotic: true,
    hasP: false,
    hasT: false,
    isPEA: false,
    isArtifact: false,
    irregular: 1.0,
    p_amp: 0,
    qrs_amp: 0,
    t_amp: 0,
    vf_amp: 0.4,
    noise_amp: 0.02,
    vf_hold_duration: 3, // Pidetään arvoa 3 näytteen ajan
  },
  vt_pulseless: {
    generatorType: "pqrst",
    baseHR: 180,
    isFlat: false,
    isChaotic: false,
    hasP: false,
    hasT: false,
    irregular: 0.01,
    p_amp: 0,
    qrs_amp: 1.5,
    qrs_width: 0.16,
    q_amp_factor: 0.05,
    s_amp_factor: 0.1,
    t_amp: -0.2,
    t_width: 0.1,
    pr_interval: 0,
    t_mean_offset: 0.2,
    isPEA: true,
    isArtifact: false,
    noise_amp: 0.02,
  },
  asystole: {
    generatorType: "flatline",
    baseHR: 0,
    isFlat: true,
    isChaotic: false,
    hasP: false,
    hasT: false,
    isPEA: false,
    isArtifact: false,
    irregular: 0,
    p_amp: 0,
    qrs_amp: 0,
    t_amp: 0,
    noise_amp: 0.015,
  },
  pea: {
    generatorType: "pqrst",
    baseHR: 20, // Hitaampi taajuus, lähempänä agonaalista
    isFlat: false,
    isChaotic: false,
    hasP: false, // Ei P-aaltoja
    hasT: true, // T-aalto voi olla olemassa, mutta muokataan sitä
    isPEA: true, // TÄRKEÄÄ: Pidetään true, jotta se on pulssiton
    isArtifact: false,
    irregular: 0.15, // Lisätään hieman epäsäännöllisyyttä
    p_amp: 0.1, // Ei P-aallon amplitudia
    qrs_amp: 0.8, // Pienennetään hieman QRS-amplitudia
    qrs_width: 0.18, // Leveämpi QRS, kuten agonaalisessa
    q_amp_factor: 0.05, // Pienempi Q-aalto
    s_amp_factor: 0.1, // Pienempi S-aalto
    t_amp: -0.15, // Käänteinen tai matala T-aalto
    t_width: 0.15, // Leveämpi T-aalto
    pr_interval: 0, // Ei PR-intervallia, koska ei P-aaltoa
    t_mean_offset: 0.3, // Säädetään T-aallon paikkaa QRS:n jälkeen
    noise_amp: 0.025, // Vähennetty häiriötä
  },
  cpr_artifact: {
    generatorType: "artifact",
    baseHR: 0,
    isFlat: false,
    isChaotic: false,
    hasP: false,
    hasT: false,
    isPEA: false,
    isArtifact: true,
    qrs_amp: 0,
    p_amp: 0,
    t_amp: 0,
    pr_interval: 0,
    qrs_width: 0,
    artifactType: "cpr",
    artifact_freq: 110,
    artifact_amp: 1.8,
    artifact_shape_factor: 0.15,
    noise_amp: 0.01,
    spo2Value: 0,
    spo2Shape: "no_signal",
    cpr_abp_shape: "damped",
    cpr_abp_sys: 70,
    cpr_abp_dia: 25,
    etco2ValueKpa: 2.0,
    etco2Shape: "cpr_low_flow",
    respiratoryRate: 10,
  },
};
